server:
  port: 5003

jwt:
  secret: SW50ZXJiYW5rLVNlY3JldC1LZXktMjAyNi1NaWNyb3NlcnZpY2lvcy1BcmNoaXRlY3R1cmE=

grpc:
  server:
    port: 9092
  client:
    auth-service:
      address: static://auth-service:9090
      negotiation-type: plaintext
    pagos-service:
      address: static://pagos-service:9091
      negotiation-type: plaintext
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/interbank_dev}
    username: ${SPRING_DATASOURCE_USERNAME:equipo_dev}
    password: ${SPRING_DATASOURCE_PASSWORD:secreta_dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Lima
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-broker:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
