server.port=5002
grpc.server.port=9091

# BD
spring.datasource.url=jdbc:postgresql://db:5432/interbank_dev
spring.datasource.username=equipo_dev
spring.datasource.password=secreta_dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MAGIA DOCKER: Aquí reemplazamos la IP de Tailscale por el nombre del contenedor
grpc.client.auth-service.address=static://auth-service:9090
grpc.client.auth-service.negotiation-type=plaintext

# Prometheus / Actuator
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
