syntax = "proto3";

package com.interbank.grpc;

option java_multiple_files = true;

// Servicio de Auth
service AuthService {
  rpc ValidateToken (TokenRequest) returns (AuthResponse);
}

// Servicio de Pagos
service PagosService {
  rpc ProcessPayment (PaymentRequest) returns (PaymentResponse);
}

message TokenRequest { string token = 1; }
message AuthResponse { bool isValid = 1; string userId = 2; }

message PaymentRequest { string userId = 1; double amount = 2; string token = 3; }
message PaymentResponse { bool success = 1; string transactionId = 2; }
