version: '3.8'

services:
  # 1. Tu Base de Datos Compartida
  db:
    image: postgres:16
    container_name: interbank-db-local
    environment:
      POSTGRES_USER: equipo_dev
      POSTGRES_PASSWORD: secreta_dev
      POSTGRES_DB: interbank_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interbank-red

  # 2. Auth Service (Dev 1)
  auth-service:
    build: ./auth-service
    container_name: interbank-auth
    ports:
      - "5001:5001"
      - "9090:9090"
    networks:
      - interbank-red

  # 3. Pagos Service (Tú)
  pagos-service:
    build: ./pagos-service
    container_name: interbank-pagos
    ports:
      - "5002:5002"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/interbank_dev
      - GRPC_CLIENT_AUTH_SERVICE_ADDRESS=static://auth-service:9090
    networks:
      - interbank-red

  # 4. Transferencias Service (Dev 3)
  transferencia-service:
    build: ./transferencia-service
    container_name: interbank-transferencias
    ports:
      - "5003:5003"
      - "9092:9092"
    environment:
      - GRPC_CLIENT_AUTH_SERVICE_ADDRESS=static://auth-service:9090
      - GRPC_CLIENT_PAGOS_SERVICE_ADDRESS=static://pagos-service:9091
    networks:
      - interbank-red

  # 5. Usuarios Service (Python)
  #usuarios-service:
   # build: ./usuarios-service
    #container_name: interbank-usuarios
    #ports:
     # - "5004:5003"
    #networks:
     # - interbank-red

  # 6. Api_Gateway
  api-gateway:
    build: ./api-gateway
    container_name: interbank-gateway
    ports:
      - "8081:8080"
    networks:
      - interbank-red
    depends_on:
      - pagos-service
      - transferencia-service
     # - usuarios-service
  # 7. Zookeeper (Manager de Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: interbank-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - interbank-red
  # 8. Apache Kafka (Broker de Mensajes)
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: interbank-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"  # <-- CAMBIO AQUÍ: Ahora mapeamos al 9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # <-- CAMBIO AQUÍ: Anunciamos Kafka en el puerto 9093 para localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - interbank-red
networks:
  interbank-red:
    driver: bridge

volumes:
  postgres_data:
