global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'interbank-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'pagos-service:5002', 'transferencia-service:5003', 'auth-service:5001']