apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pagos-service-hpa
  namespace: interbank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pagos-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
    scaleDown:
      stabilizationWindowSeconds: 90
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transferencia-service-hpa
  namespace: interbank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transferencia-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
    scaleDown:
      stabilizationWindowSeconds: 90
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
