apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-service
  namespace: interbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos-service
  template:
    metadata:
      labels:
        app: pagos-service
    spec:
      containers:
        - name: pagos-service
          image: interbank-distribuidov3-pagos-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/interbank_dev
            - name: SPRING_DATASOURCE_USERNAME
              value: equipo_dev
            - name: SPRING_DATASOURCE_PASSWORD
              value: secreta_dev
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:9092
            - name: GRPC_CLIENT_AUTH_SERVICE_ADDRESS
              value: static://auth-service:9090
            - name: SPRING_REDIS_HOST
              value: redis
            - name: TZ
              value: America/Lima
          resources:
            requests:
              memory: "320Mi"
              cpu: "150m"
            limits:
              memory: "576Mi"
              cpu: "600m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 5002
            failureThreshold: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 5002
            periodSeconds: 20
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    for i in $(seq 1 60); do
                      if wget -q -O- http://localhost:5002/actuator/health 2>/dev/null; then
                        TOKEN=$(wget -q -O- --post-data='{"username":"admin","password":"admin123"}' \
                          --header='Content-Type: application/json' \
                          http://auth-service:5001/auth/login 2>/dev/null | sed 's/.*"token":"\([^"]*\)".*/\1/')
                        wget -q -O- --post-data='{"amount":1,"cuentaDestino":"WARMUP"}' \
                          --header="Authorization: Bearer $TOKEN" \
                          --header='Content-Type: application/json' \
                          http://localhost:5002/pagos/procesar 2>/dev/null
                        echo "[WARM-UP] Pagos precalentado"
                        break
                      fi
                      sleep 3
                    done
---
apiVersion: v1
kind: Service
metadata:
  name: pagos-service
  namespace: interbank
spec:
  selector:
    app: pagos-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
    - name: grpc
      port: 9091
      targetPort: 9091
