apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: interbank
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:5001']

      - job_name: 'pagos-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['pagos-service:5002']

      - job_name: 'transferencia-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['transferencia-service:5003']

      - job_name: 'kafka'
        scrape_interval: 30s
        scrape_timeout: 25s
        static_configs:
          - targets: ['kafka-exporter:9308']

      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
