jwt:
  secret: SW50ZXJiYW5rLVNlY3JldC1LZXktMjAyNi1NaWNyb3NlcnZpY2lvcy1BcmNoaXRlY3R1cmE=

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-broker:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379
      timeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
